name: "Auto name"
description: "Rename this repo with stars and forks number"
inputs:
  github_token:
    description: ${{ secrets.GITHUBTOKEN }}
    required: true
  actor:
    description: thuongtruong1009
    required: true
  icon:
    description: 'activity'
  color:
    description: purple
  label:
    description: 'GitHub'
  repository:
    description: thuongtruong1009/a_repo_with_0_stars_and_0_forks
outputs: {}
runs:
  using: "node12"
  main: "index.js"
